// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRnN3RRUxqVatuGO9sDfidam5JFjDTFRY',
    appId: '1:46476919256:web:6c985a9886c67b5073f2ad',
    messagingSenderId: '46476919256',
    projectId: 'live-location-tracker-zain',
    authDomain: 'live-location-tracker-zain.firebaseapp.com',
    storageBucket: 'live-location-tracker-zain.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQD9mUA_a2b0DAABp-PW-WrBCFx8MsCcY',
    appId: '1:46476919256:android:37a3a04786cf522573f2ad',
    messagingSenderId: '46476919256',
    projectId: 'live-location-tracker-zain',
    storageBucket: 'live-location-tracker-zain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-N3U08ZdZamkjbAeUsOunExewTlT8D7Q',
    appId: '1:46476919256:ios:51507d68cc8abbf473f2ad',
    messagingSenderId: '46476919256',
    projectId: 'live-location-tracker-zain',
    storageBucket: 'live-location-tracker-zain.firebasestorage.app',
    iosBundleId: 'com.example.liveLocationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-N3U08ZdZamkjbAeUsOunExewTlT8D7Q',
    appId: '1:46476919256:ios:51507d68cc8abbf473f2ad',
    messagingSenderId: '46476919256',
    projectId: 'live-location-tracker-zain',
    storageBucket: 'live-location-tracker-zain.firebasestorage.app',
    iosBundleId: 'com.example.liveLocationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRnN3RRUxqVatuGO9sDfidam5JFjDTFRY',
    appId: '1:46476919256:web:1fe8396eaa6068bf73f2ad',
    messagingSenderId: '46476919256',
    projectId: 'live-location-tracker-zain',
    authDomain: 'live-location-tracker-zain.firebaseapp.com',
    storageBucket: 'live-location-tracker-zain.firebasestorage.app',
  );
}
